services:
  linux-lab:
    environment:
      - TZ=America/New_York
    build: .
    container_name: linux-lab
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
    command: bash
    
